[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pygments>=2.19.1",
    "requests>=2.32.3",
    "sqlparse>=0.5.3",
    "streamlit>=1.43.1",
]
